version: '3.8'

services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    networks:
      - poll-tier
      - back-tier
    restart: always
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:6.2-alpine
    networks:
      - back-tier
    restart: always

  worker:
    build: ./worker
    networks:
      - back-tier
    restart: always
    depends_on:
      - redis
      - db
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - back-tier
    restart: always

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - result-tier
      - back-tier
    restart: always
    depends_on:
      - db
    env_file:
      - .env

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: